/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL_481_Homework_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

   

    @Test
    public void NullArrays(){
        assertNull(App.concatenateArraysAndReturnMeanAndKthOrderStatistics(null, null, null, 5));
    }

    @Test
    public void NullArray(){
        assertNull(App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {3.14, 2.879,14}, null, new double[] {7.5,36.98,36.9}, 2));
    }

    @Test
    public void EmptyArrays(){
        assertNull(App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {}, new double[] {}, new double[] {}, 3));
    }



    @Test
    public void NegativeK(){
        assertNull(App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {1,2,5.0}, new double[] {10,20,30}, new double[] {10, 76.58}, -1));
    }

    @Test
    public void TooBigK(){
        assertNull(App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {1,2,5.0}, new double[] {10,20,30}, new double[] {10, 76.58}, 10));
    }

    @Test
    public void NullK(){
        assertNull(App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {1,2,5.0}, new double[] {10,20,30}, new double[] {10, 76.58}, null));
    }


    @Test
    public void ValidParameters(){
        assertArrayEquals(new double[] {72.1431,0}, App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {300.786, -18,0}, new double[] {5.7864}, new double[] {}, 2));
    }

    @Test
    public void ValidParameters2(){
        assertArrayEquals(new double[] {0,10}, App.concatenateArraysAndReturnMeanAndKthOrderStatistics(new double[] {-30,10,20}, new double[] {-10,-20,0}, new double[] {30}, 5));
    }




}
