/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL_481_Homework_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    @Test 
    public void NullArray1(){
        assertNull(App.getGreaterOrLowerOrIntersectingElements(null, null, 15.0, "asd"));
    }

}
