/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL_481_Homework_1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }


    public static double[] getGreaterOrLowerOrIntersectingElements(double [] array1 , double [] array2 , Double d , String command){

        /*
            This method finds the elements that are greater or less than the element d according to the given command.
            If command is "greater" then this method finds and returns elements that are greater than d.
            If command is "lower" then this method finds and returns elements that are less than d.
            If command is "intersection" then this method finds and returns elements that are in both array1 and array2. In this case parameter d is meaningless.
            If an error is occur or some parameters are invalid then this method returns null. 

        */



        if(array1 == null)
            return null;


        return null;
    }

}
